topfunky/gruff

lib/gruff/base.rb

Adds support for a different title font and an option for whether to draw the title bolded or not.

Add extra options for title appearance

---

lib/gruff/base.rb
test/test_base.rb

Completes: [issue 137](https://github.com/topfunky/gruff/issues/137)

Allow labels to be non strings

---

.rubocop_todo.yml
Rakefile
gruff.gemspec

$ bundle exec rubocop --only Layout/SpaceBeforeBlockBraces --auto-correct

Rubocop: Add space before block brace

---

.rubocop_todo.yml
Rakefile
lib/gruff/base.rb

$ bundle exec rubocop --only Style/Semicolon --auto-correct

Rubocop: Remove semicolons

---

.rubocop_todo.yml
Rakefile
gruff.gemspec
lib/gruff/accumulator_bar.rb
lib/gruff/mini/legend.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/spider.rb
test/test_accumulator_bar.rb
test/test_area.rb
test/test_net.rb
test/test_pie.rb

$ bundle exec rubocop --only Layout/SpaceInsideBlockBraces --auto-correct

Rubocop: Add space inside block braces

---

lib/gruff/base.rb
test/test_base.rb

It raised an error with setting the minimum_value or maximum_value before calling the data() method.
Close #156

Fix error of “comparison of Integer with nil failed”

---

lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb

It complicates the structure and is difficult to understand

refactor: Do not mix raw data with normalized data

---

.rubocop.yml
.rubocop_todo.yml
lib/gruff.rb
lib/gruff/accumulator_bar.rb
lib/gruff/area.rb
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/bezier.rb
lib/gruff/dot.rb
lib/gruff/line.rb
lib/gruff/mini/legend.rb
lib/gruff/net.rb
lib/gruff/photo_bar.rb
lib/gruff/pie.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/spider.rb
lib/gruff/stacked_area.rb
lib/gruff/stacked_bar.rb
lib/gruff/stacked_mixin.rb
lib/gruff/store/base_data.rb
lib/gruff/store/custom_data.rb
lib/gruff/store/xy_data.rb
test/test_pie.rb

Because it's hard to debug if it put different values in the array

refactor: Add data structure classes

---

.rubocop_todo.yml
lib/gruff/accumulator_bar.rb
lib/gruff/base.rb
lib/gruff/scene.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/spider.rb
test/test_accumulator_bar.rb
test/test_area.rb
test/test_bar.rb
test/test_dot.rb
test/test_line.rb
test/test_net.rb

$ bundle exec rubocop --only Style/CollectionMethods --auto-correct

Rubocop: Fix Style/CollectionMethods

---

lib/gruff/base.rb

Seem that the solution are not valid.
I guess that the error will be solved by https://github.com/topfunky/gruff/pull/305
Revert #295
Revert #298

Revert expanding cache size

---

.rubocop_todo.yml
lib/gruff/bar_conversion.rb
lib/gruff/stacked_area.rb

Remove duplicated code around data storing.

Rubocop: Fix Style/IdenticalConditionalBranches

---

lib/gruff/base.rb
lib/gruff/bullet.rb
lib/gruff/dot.rb
lib/gruff/net.rb
lib/gruff/photo_bar.rb
lib/gruff/pie.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/spider.rb

1. It's tough to know which constants are from RMagick
2. By including, it will add a lot of methods, etc. Then the Gruff object size will be increased.

refactor: Do not include RMagick into Base class

---

test/test_bar.rb
test/test_side_bar.rb
test/test_sidestacked_bar.rb

Test: Added a test that allows multiple calls to the draw method

---

lib/gruff/area.rb
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/histogram.rb
lib/gruff/line.rb
lib/gruff/net.rb
lib/gruff/pie.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/spider.rb
lib/gruff/stacked_area.rb
lib/gruff/stacked_bar.rb
test/test_line.rb
test/test_scatter.rb

Remove the getter method in attributes  for configuration

---

lib/gruff/base.rb

Doc: Update description of Base#theme=

---

.rubocop.yml
.travis.yml
gruff.gemspec

Drop support of Ruby v2.3.x

---

lib/gruff/scatter.rb

Use the same name attribute used in Gruff::Line.

Rename enable_vertical_line_markers attribute to show_vertical_markers

---

.rubocop_todo.yml
gruff.gemspec

https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdateassignment

Rubocop: Remove unnecessary date setting in gemspec

---

.travis.yml

Travis: Remove phostscript dependency because it was removed at #495

---

.github/workflows/ci.yml

Ref: https://github.com/marketplace/actions/rubocop-problem-matchers

CI: Add rubocop-problem-matchers-action

---

rails_generators/gruff/templates/controller.rb

The `Gruff::Base#to_blob` was marked as deprecated

Update rails template

---

gruff.gemspec

It has memory leak fix.
Ref. https://github.com/rmagick/rmagick/pull/1406

Update dependent RMagick version to 5.3.0 or later
