topfunky/gruff

gruff.gemspec
lib/gruff/base.rb

Gruff now needs rmagic version >= 2.13.4, since that's when rmagick.rb
was introduced.
Tested with:
* ruby-2.2.1
* ruby-1.9.3
* jruby-1.7.19
If the ability to use older version of rmagick is desired, that can be done by something along the lines of:
begin
require 'rmagic'
rescue LoadError
require "RMagick'
end

Fix rmagick deprecation warning by requiring rmagic instead of Rmagick.

---

gruff.gemspec

Ruby >= 2.2 no longer comes with test-unit built in.

Add test-unit as a dev dependency.

---

lib/gruff/pie.rb

Today I was creating some pie graphs for which the value, not the percentage, needed to be shown as label. I didn't find a way to do it, so I implemented my own. I think it's an important feature for this kind of graph.
It's kind of a quick fix, so if you have any ideas for a better API, I would be happy to implement them.
Thanks for your awesome gem!

Showing values as labels in Pie

---

test/test_scatter.rb

Fixed the order of `x_values` and `y_values` in `test_scatter.rb`, line 28.

test/scatter.rb line 28, switched x_values and y_values argument order.

---

lib/gruff/bezier.rb

I've modified Bezier to initialize the curves from the first datum rather than zero (or more strictly, the calculated value that is stored in @graph_left and @graph_bottom). Previously, the first datum for each curve was lost, and the curves skewed by being dragged harshly down to the origin.

initialize bezier curve to start at it's first datum, not at origin.

---

README.md

Seems the linked site was already shutdown.
Close #154, #177

Remove the link to the old example site

---

.rubocop_todo.yml
Rakefile
lib/gruff/photo_bar.rb
lib/gruff/themes.rb
test/test_bar.rb
test/test_dot.rb
test/test_side_bar.rb
test/test_sidestacked_bar.rb

$ bundle exec rubocop --only Layout/TrailingEmptyLines --auto-correct

Rubocop: Remove trailing blank lines

---

.rubocop_todo.yml
lib/gruff/line.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
test/test_line.rb
test/test_sidestacked_bar.rb
test/test_spider.rb
test/test_stacked_area.rb
test/test_stacked_bar.rb

$ bundle exec rubocop --only Layout/EmptyLinesAroundMethodBody --auto-correct

Rubocop: Remove blank lines around method body

---

.rubocop_todo.yml
lib/gruff/bar_conversion.rb

$ bundle exec rubocop --only Layout/Tab --auto-correct

Rubocop: Convert tab to space indentation

---

.rubocop_todo.yml
lib/gruff/area.rb
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/dot.rb
lib/gruff/line.rb
lib/gruff/mini/legend.rb
lib/gruff/net.rb
lib/gruff/photo_bar.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/stacked_area.rb
lib/gruff/stacked_bar.rb

$ bundle exec rubocop --only Layout/EmptyLinesAroundBlockBody --auto-correct

Rubocop: Remove blank lines around block

---

.rubocop_todo.yml
Rakefile
test/test_accumulator_bar.rb
test/test_bezier.rb
test/test_dot.rb
test/test_net.rb
test/test_scatter.rb

$ bundle exec rubocop --only Layout/SpaceAfterComma --auto-correct

Rubocop: Add space after comma

---

.rubocop_todo.yml
lib/gruff/bullet.rb
lib/gruff/pie.rb
lib/gruff/spider.rb

$ bundle exec rubocop --only Layout/ExtraSpacing --auto-correct

Rubocop: Fix extra spaces

---

.rubocop_todo.yml
gruff.gemspec

Because Ruby 3.0 is scheduled to be released this year.

Remove the upper limit from the required Ruby version

---

.rubocop_todo.yml
gruff.gemspec

If you use the old rmagick, it might work with ruby 1.9…

Adjust the lower limit of required_ruby_version

---

.rubocop_todo.yml
lib/gruff/area.rb
lib/gruff/deprecated.rb
lib/gruff/scene.rb
lib/gruff/spider.rb
lib/gruff/stacked_area.rb
lib/gruff/stacked_bar.rb
lib/gruff/stacked_mixin.rb
test/test_mini_bar.rb
test/test_side_bar.rb

$ bundle exec rubocop --only Layout/LeadingEmptyLines --auto-correct

Rubocop: Remove leading blank lines

---

.rubocop_todo.yml
lib/gruff/base.rb

$ bundle exec rubocop --only Layout/AssignmentIndentation --auto-correct

Rubocop: Fix indentation of assignment

---

.rubocop_todo.yml
lib/gruff/bar.rb
lib/gruff/mini/legend.rb
lib/gruff/spider.rb
lib/gruff/stacked_bar.rb
test/test_net.rb
test/test_scene.rb

$ bundle exec rubocop --only Layout/SpaceInsideParens --auto-correct

Rubocop: Remove spaces inside parens

---

.rubocop_todo.yml
Rakefile

$ bundle exec rubocop --only Layout/SpaceAroundBlockParameters --auto-correct

Rubocop: Add space after block parameter

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/stacked_mixin.rb

$ bundle exec rubocop --only Style/HashEachMethods --auto-correct

Rubocop: Use each_key instead of keys.each

---

.rubocop_todo.yml
lib/gruff/bar.rb

$ bundle exec rubocop --only Style/MultilineIfThen --auto-correct

Rubocop: Remove ‘then’ from if statement

---

.rubocop_todo.yml
lib/gruff/base.rb

$ bundle exec rubocop --only Style/OneLineConditional --auto-correct

Rubocop: Use ternary operator instead of oneline if statement

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/line.rb
test/gruff_test_case.rb
test/image_compare.rb

$ bundle exec rubocop --only Style/ParallelAssignment --auto-correct

Rubocop: Avoid parallel assignment for readability

---

.rubocop_todo.yml
test/image_compare.rb

$ bundle exec rubocop --only Lint/DeprecatedClassMethods --auto-correct

Rubocop: Use File.exist? instead of deprecated method

---

.rubocop.yml
.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/dot.rb
lib/gruff/net.rb
lib/gruff/pie.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
test/gruff_test_case.rb
test/test_bar.rb
test/test_line.rb
test/test_pie.rb
test/test_scatter.rb

$ bundle exec rubocop --only Layout/AccessModifierIndentation --auto-correct

Rubocop: Fix indentation of access modifiers

---

.rubocop_todo.yml
lib/gruff/themes.rb

$ bundle exec rubocop --only Layout/EmptyComment --auto-correct

Rubocop: Remove empty comments

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/bullet.rb
lib/gruff/line.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
test/gruff_test_case.rb
test/test_area.rb
test/test_bar.rb
test/test_dot.rb
test/test_line.rb
test/test_net.rb
test/test_pie.rb
test/test_scatter.rb
test/test_sidestacked_bar.rb
test/test_spider.rb

$ bundle exec rubocop --only Layout/SpaceAroundEqualsInParameterDefault --auto-correct

Rubocop: Add space around ‘=‘ of default parameter

---

.rubocop_todo.yml
test/gruff_test_case.rb

$ bundle exec rubocop --only Lint/UnifiedInteger --auto-correct

Rubocop: Use Integer instead of Fixnum

---

.rubocop_todo.yml
Rakefile
lib/gruff/bar.rb
lib/gruff/bar_conversion.rb
lib/gruff/base.rb
lib/gruff/bullet.rb
lib/gruff/dot.rb
lib/gruff/mini/legend.rb
lib/gruff/net.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/spider.rb
lib/gruff/stacked_area.rb
test/test_bar.rb
test/test_dot.rb
test/test_scatter.rb

$ bundle exec rubocop --only Layout/SpaceAroundOperators --auto-correct

Rubocop: Add space around operators

---

.rubocop_todo.yml
lib/gruff/bullet.rb

$ bundle exec rubocop --only Lint/RedundantSplatExpansion --auto-correct

Rubocop: Remove redundant splat expansion

---

.rubocop_todo.yml
lib/gruff/scatter.rb

$ bundle exec rubocop --only Layout/BlockAlignment --auto-correct

Rubocop: Fix indentation in block

---

.rubocop.yml
.rubocop_todo.yml
Rakefile
lib/gruff/base.rb
lib/gruff/pie.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/themes.rb
test/test_accumulator_bar.rb
test/test_bar.rb
test/test_bezier.rb
test/test_bullet.rb
test/test_dot.rb
test/test_line.rb
test/test_pie.rb
test/test_scatter.rb

$ bundle exec rubocop --only Style/HashSyntax --auto-correct

Rubocop: Fix Hash syntax style

---

.rubocop_todo.yml
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/line.rb
lib/gruff/stacked_bar.rb

$ bundle exec rubocop --only Style/ParenthesesAroundCondition --auto-correct

Rubocop: Remove unnecessary parentheses in condition

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/side_stacked_bar.rb
test/gruff_test_case.rb
test/test_accumulator_bar.rb
test/test_bar.rb
test/test_dot.rb
test/test_line.rb
test/test_side_bar.rb

$ bundle exec rubocop --only Layout/SpaceInsideHashLiteralBraces --auto-correct

Rubocop: Add space around Hash literal braces

---

.rubocop_todo.yml
Rakefile
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/bullet.rb
lib/gruff/line.rb
lib/gruff/photo_bar.rb
lib/gruff/scene.rb
lib/gruff/side_bar.rb
lib/gruff/stacked_bar.rb
test/image_compare.rb

$ bundle exec rubocop --only Layout/EmptyLineAfterGuardClause --auto-correct

Rubocop: Add blank line after guard clause

---

.rubocop_todo.yml
test/test_bezier.rb
test/test_bullet.rb
test/test_spider.rb

$ bundle exec rubocop --only Layout/MultilineArrayLineBreaks --auto-correct

Rubocop: Fix alignment of multiline array

---

.rubocop_todo.yml
Rakefile

$ bundle exec rubocop --only Layout/MultilineHashKeyLineBreaks --auto-correct

Rubocop: Fix alignment of multiline hash

---

.rubocop_todo.yml
test/test_legend.rb

$ bundle exec rubocop --only Style/SelfAssignment --auto-correct

Rubocop: Use self-assignment shorthand +=

---

.rubocop_todo.yml
lib/gruff/base.rb

$ bundle exec rubocop --only Layout/SpaceInsideRangeLiteral --auto-correct

Rubocop: Remove space inside Range literal

---

.rubocop_todo.yml
lib/gruff/bar.rb

$ bundle exec rubocop --only Style/RedundantConditional --auto-correct

Rubocop: Remove redundant conditional

---

.rubocop_todo.yml
lib/gruff/scatter.rb
lib/gruff/spider.rb

$ bundle exec rubocop --only Layout/ArgumentAlignment --auto-correct

Rubocop: Fix argument alignment

---

.rubocop_todo.yml
lib/gruff/scene.rb

$ bundle exec rubocop --only Style/InverseMethods --auto-correct

Rubocop: Use reject instead of inverting select

---

.rubocop_todo.yml
Rakefile
gruff.gemspec
lib/gruff.rb
lib/gruff/base.rb
lib/gruff/themes.rb
test/test_area.rb
test/test_bar.rb
test/test_dot.rb
test/test_line.rb
test/test_net.rb
test/test_scene.rb

$ bundle exec rubocop --only Style/PercentLiteralDelimiters --auto-correct

Rubocop: Fix percent literal delimiters

---

gruff.gemspec

Because the added fonts at #246 will increase gem file size

Reject test directory from gem package in order to reduce the Gem file size

---

test/test_scatter.rb

When run test, it causes following error on my environment:
* OS: macOS 10.15.4
* Ruby: ruby 2.7.1
```
ERROR["test_custom_label_format", #<Minitest::Reporters::Suite:0x00007fa05d7173c0 @name="TestGruffScatter">, 22.75117299996782]
test_custom_label_format#TestGruffScatter (22.75s)
Minitest::UnexpectedError:         NameError: uninitialized constant TestGruffScatter::Date
Did you mean?  Data
/Users/watson/prj/gruff/test/test_scatter.rb:66:in `block in test_custom_label_format'
/Users/watson/prj/gruff/test/test_scatter.rb:66:in `each'
/Users/watson/prj/gruff/test/test_scatter.rb:66:in `map'
/Users/watson/prj/gruff/test/test_scatter.rb:66:in `test_custom_label_format'
```

Test: Require ‘date’ to fix “NameError: uninitialized constant TestGruffScatter::Date” error

---

lib/gruff/area.rb

This patch will remove following warning message at running tests.
```
$ rake
/Users/watson/prj/gruff/lib/gruff/area.rb:19: warning: assigned but unused variable - prev_x
Started with run options --seed 11247
```

Remove unused variables

---

Gemfile

This PR uses `https` to connect to rubygems.org for metadata.

Gemfile: refer to https for rubygems.org

---

.rubocop_todo.yml
lib/gruff/mini/legend.rb

$ bundle exec rubocop --only Layout/FirstArgumentIndentation --auto-correct

Rubocop: Fix indentation of first argument

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/deprecated.rb
lib/gruff/mini/bar.rb
lib/gruff/mini/legend.rb
lib/gruff/mini/pie.rb
lib/gruff/mini/side_bar.rb
lib/gruff/themes.rb

$ bundle exec rubocop --only Layout/EmptyLinesAroundModuleBody --auto-correct

Rubocop: Remove blank line around module body

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/line.rb
lib/gruff/side_bar.rb

$ bundle exec rubocop --only Style/RedundantSelf --auto-correct

Rubocop: Remove redundant self

---

.rubocop_todo.yml
Rakefile
lib/gruff/scene.rb
test/test_area.rb
test/test_net.rb
test/test_pie.rb
test/test_sidestacked_bar.rb
test/test_spider.rb

$ bundle exec rubocop --only Style/RedundantReturn --auto-correct

Rubocop: Remove redundant return

---

.rubocop_todo.yml
test/gruff_test_case.rb
test/test_area.rb
test/test_bar.rb
test/test_base.rb
test/test_dot.rb
test/test_legend.rb
test/test_line.rb
test/test_net.rb
test/test_sidestacked_bar.rb
test/test_stacked_area.rb
test/test_stacked_bar.rb

$ bundle exec rubocop --only Style/TrailingCommaInHashLiteral --auto-correct

Rubocop: Remove trailing comma in Hash

---

.rubocop_todo.yml
lib/gruff/area.rb
lib/gruff/base.rb
lib/gruff/bezier.rb
lib/gruff/line.rb
lib/gruff/photo_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/stacked_area.rb
test/test_line.rb

$ bundle exec rubocop --only Style/EmptyLiteral --auto-correct

Rubocop: Use literal instead of new method

---

.rubocop_todo.yml
test/image_compare.rb

bundle exec rubocop --only Style/VariableInterpolation --auto-correct

Rubocop: Fix style of string interpolation with variable

---

.rubocop_todo.yml
lib/gruff/net.rb

$ bundle exec rubocop --only Style/ColonMethodCall --auto-correct

Rubocop: Fix method calling style

---

.rubocop_todo.yml
lib/gruff/scene.rb
test/test_line.rb
test/test_net.rb

$ bundle exec rubocop --only Style/SymbolProc --auto-correct

Rubocop: Use symbols as proc when possible

---

.rubocop_todo.yml
lib/gruff/side_bar.rb

$ bundle exec rubocop --only Style/RedundantParentheses --auto-correct

Rubocop: Remove redundant parentheses

---

.rubocop_todo.yml
lib/gruff/bullet.rb

$ bundle exec rubocop --only Style/PreferredHashMethods --auto-correct

Rubocop: Use Hash#key? instead of Hash#has_key?

---

.rubocop_todo.yml
lib/gruff/bullet.rb
lib/gruff/mini/legend.rb
lib/gruff/scene.rb
lib/gruff/side_stacked_bar.rb
test/test_area.rb
test/test_base.rb
test/test_bezier.rb
test/test_bullet.rb
test/test_labels_for_null_data.rb
test/test_net.rb
test/test_photo.rb
test/test_pie.rb
test/test_scene.rb
test/test_side_bar.rb
test/test_sidestacked_bar.rb
test/test_spider.rb
test/test_stacked_bar.rb

$ bundle exec rubocop --only Style/StringLiterals --auto-correct

Rubocop: Fix String literal style

---

.rubocop_todo.yml
lib/gruff/bar.rb
lib/gruff/photo_bar.rb
lib/gruff/scatter.rb
test/test_bar.rb
test/test_line.rb
test/test_pie.rb
test/test_spider.rb

$ bundle exec rubocop --only Style/MethodCallWithoutArgsParentheses --auto-correct

Rubocop: Remove redundant parentheses in method calling without args

---

.rubocop_todo.yml
lib/gruff/bar.rb

$ bundle exec rubocop --only Style/AndOr --auto-correct

Rubocop: Use && instead of and

---

.rubocop_todo.yml
lib/gruff/side_stacked_bar.rb

$ bundle exec rubocop --only Lint/UnusedMethodArgument --auto-correct

Rubocop: Remove unused arguement

---

lib/gruff/base.rb

Sometimes I get a "cache resources exhausted" error in CI.
To avoid this error, it needs to expand cache memory size.

Expand cache memory size to avoid “cache resources exhausted” error in ImageMagick

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/line.rb

$ bundle exec rubocop --only Style/ZeroLengthPredicate --auto-correct

Rubocop: Fix Style/ZeroLengthPredicate

---

lib/gruff/base.rb

Related to #295, https://travis-ci.org/github/topfunky/gruff/jobs/679345477

Expand disk size limitation to avoid “cache resources exhausted” error in ImageMagick

---

.rubocop_todo.yml
lib/gruff/scene.rb

$ bundle exec rubocop --only Style/PerlBackrefs --auto-correct

Rubocop: Fix Style/PerlBackrefs

---

.rubocop_todo.yml
lib/gruff/base.rb
lib/gruff/bullet.rb
lib/gruff/deprecated.rb
lib/gruff/dot.rb
lib/gruff/photo_bar.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
test/test_accumulator_bar.rb
test/test_bar.rb
test/test_dot.rb
test/test_line.rb
test/test_scatter.rb

$ bundle exec rubocop --only Style/CommentAnnotation --auto-correct

Rubocop: Fix Style/CommentAnnotation

---

.rubocop_todo.yml
lib/gruff/base.rb

$ bundle exec rubocop --only Style/RedundantSort --auto-correct

Rubocop: Fix Style/RedundantSort

---

test/test_base.rb

When I set the minimum before the data() method, the minimum value was updated in data().
The issue should be solved by https://github.com/topfunky/gruff/pull/314
Related to #257

Test: Add test cases for minimum/maximum value

---

lib/gruff/line.rb
lib/gruff/scatter.rb
test/test_line.rb
test/test_scatter.rb

```ruby
g = Gruff::Line.new
obj = Object.new
def obj.to_a
[1, 2, 3, 4, 5]
end
g.dataxy('Apples', obj, obj)
```
The above code will raise an exception even if the argument object can behave as Array.

Fix an exception when using an object as an argument that behaves as an Array

---

.rubocop_todo.yml
test/gruff_test_case.rb

$ bundle exec rubocop --only Style/Alias --auto-correct

Rubocop: Fix Style/Alias

---

lib/gruff/base.rb

`get_maximum_by_stack` is defined at `Gruff::Base::StackedMixin` too.

refactor: Remove duplicated get_maximum_by_stack method

---

lib/gruff/base.rb
lib/gruff/dot.rb
lib/gruff/mini/legend.rb
lib/gruff/net.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/spider.rb

Basically, the font will be set at `Gruff::Base#font=` method into `Magick::Draw` object.

refactor: Set the font if only needed

---

test/support/appearance_assertion.rb

Some tests have several assertion.
If use `skip`, subsequent tests are not performed

Test: Use early return instead of skip

---

lib/gruff/base.rb

scale value was set up via `setup` method.

refactor: Avoid using Renderer.instance directly outside Renderer class

---

lib/gruff/scatter.rb
test/test_scatter.rb

It raised an error with setting the minimum_x_value or maximum_value before calling the dataxy() method with Gruff:: Scatter.
Related to #366

Fix error of “comparison of Integer with nil failed”

---

lib/gruff/patch/rmagick.rb

This patch will remove following warning message.
```
$ bundle exec rake
/opt/gruff/lib/gruff/patch/rmagick.rb:16: warning: method redefined; discarding old stroke_opacity
```

refactor: Remove stroke_opacity before overriding to get rid of warning message

---

lib/gruff/base.rb
test/test_base.rb

```ruby
g = Gruff::Bar.new
g.title = ''
g.data 'hoge', [20, 30, 0, 0]
g.write('test.png')
```
```
$ ruby test.rb
Traceback (most recent call last):
6: from t.rb:7:in `<main>'
5: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gruff-0.9.0/lib/gruff/base.rb:388:in `write'
4: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gruff-0.9.0/lib/gruff/bar.rb:35:in `draw'
3: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gruff-0.9.0/lib/gruff/base.rb:416:in `draw'
2: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gruff-0.9.0/lib/gruff/base.rb:655:in `draw_title'
1: from /Users/watson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gruff-0.9.0/lib/gruff/renderer/text.rb:39:in `metrics' …
```

Fix "`get_type_metrics': no text to measure" exception with empty title

---

lib/gruff/base.rb
lib/gruff/renderer/renderer.rb

Refactored Gruff::Base #setup_graph_measurements to use private methods to calculate each measurement. This moves the intertwined calculations based on hidden aspects of the graph to separate methods to make the decision points easier to follow.
No functional changes were made to the code as part of this PR.
Extracted the bulk of this from PR #443.  That PR will be refactored to follow this PR.
It is cleaner to have the refactor in a separate PR to make the follow-on PR easier to understand.  This will also allow for resolution of test failures that are related to the refactor before adding in additional new code changes.

refactor Gruff::Base #setup_graph_measurements to reduce complexity

---

lib/gruff/renderer/text.rb
test/test_render_text.rb

When run following test code with old ImageMagick, it causes SEGV.
This PR will avoid SEGV.
```
require 'gruff'
g = Gruff::Line.new
g.data :Jimmy, [25, 36, 86, 39, 25, 31, 79, 88]
g.data :Charles, [80, 54, 67, 54, 68, 70, 90, 95]
g.title = 'hello %S'
g.draw
```
```
$ ruby -e 'require "rmagick"; p Magick::Long_version'
"This is RMagick 4.2.2 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter\nBuilt with ImageMagick 6.9.7-10 Q16 x86_64 2021-04-24 http://www.imagemagick.org\nBuilt for ruby 2.7.2\nWeb page: http://rmagick.rubyforge.org\nEmail: rmagick@rubyforge.org\n"
```
```
$ ruby test.rb
/Users/watson/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/gruff-0.12.1/lib/gruff/renderer/text.rb:54: [BUG] Segmentation fault at 0x0000000000000040
ruby 2.7.2p137 (2020-10-01 …
```

Avoid SEGV caused with '%S' in Draw#get_type_metrics by old ImageMagick (6.9.9 or below) 

---

docker/Dockerfile
docker/build.sh
docker/launch.sh

Without `--platform linux/amd64`, seems that `bundle exec rake test` fails with Apple M1.
I guess it related to library compatibility (maybe ImageMagick)

Update docker files for Apple M1

---

lib/gruff/stacked_area.rb

Because
- inconsistent because Gruff::StackedArea only can change the iteration order of the data
- the order can be changed when adding data in user code

Deprecate last_series_goes_on_bottom attribute in Gruff::StackedArea

---

.rubocop_todo.yml
lib/gruff/bar.rb
lib/gruff/base.rb
lib/gruff/side_bar.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/stacked_bar.rb

Because bar_value argument is always given true

Remove redundant argument

---

gruff.gemspec
lib/gruff/renderer/renderer.rb

Fix following rmagick deprecated warning.
```
/opt/gruff/lib/gruff/renderer/renderer.rb:47: warning: passing a block without an image argument is deprecated
```

Fix deprecated in rmagick

---

.github/workflows/ci.yml
.rubocop.yml
gruff.gemspec

Ruby 2.4 has a status of End of Life at 2020-03-31
https://www.ruby-lang.org/en/downloads/branches/

Drop Ruby 2.4 support

---

lib/gruff/base.rb
lib/gruff/helper/stacked_mixin.rb
lib/gruff/side_stacked_bar.rb
lib/gruff/stacked_area.rb
lib/gruff/stacked_bar.rb

So far, the stacked graphs do not render as expected when dealing with negative values.

Raise exception if negative values were given in stacked graph

---

lib/gruff/spider.rb
test/test_spider.rb

The following error occurs when Polygon cannot be drawn.
Raise an exception appropriately because the error is difficult to understand.
```ruby
require 'gruff'
g = Gruff::Spider.new(10)
g.title = 'Sample Data'
g.data :A, [1, 2]
g.data :B, [5]
g.write("gruff_spider.png")
```
```
/home/watson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/renderer/renderer.rb:19:in `draw': non-conforming drawing primitive definition `polygon' @ error/draw.c/RenderMVGContent/4489 (Magick::ImageMagickError)
from /home/watson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/renderer/renderer.rb:19:in `finish'
from /home/watson/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/gruff-0.15.0/lib/gruff/base.rb:465:in `to_image'
from …
```

Raise exception if less data set was given in Gruff::Spider

---

lib/gruff/base.rb

```
warning: passing a block without an image argument is deprecated
```
See: https://github.com/rmagick/rmagick/issues/1270

Fix deprecation warning for Base#to_blob

---

lib/gruff/base.rb
test/test_base.rb

Fix https://github.com/topfunky/gruff/issues/616

Accept image format in Base#to_image in order to fix `no decode delegate for this image format` error

---

lib/gruff/base.rb
lib/gruff/dot.rb
lib/gruff/net.rb
lib/gruff/scatter.rb
lib/gruff/side_bar.rb
lib/gruff/spider.rb

First thing first: Thank you and congrat's for this gem! Super useful!
We needed the ability to grow the label margin in a spider chart, in order to have the labels being displayed a bit farther from the chart.
This seems to be dictated by the value of `Gruff::Base::LABEL_MARGIN`, and is not overridable.
I did a dirty temporary hack on my project (replace temporarily the constant value before generating the image, with const_set), but I'd love a cleaner solution
Pretty much the same things as for `legend_margin` (for example):
* Add an attr_writer call for label_margin
* Set the value of `@label_margin` to `Gruff::Base::LABEL_MARGIN` in `Gruff::Base#initialize_attributes`
* Replace all other references to `LABEL_MARGIN` by `@label_margin`
Let me know if you see anything that don't work …

Allow to override label margin value

---

lib/gruff/base.rb
lib/gruff/renderer/renderer.rb
lib/gruff/spider.rb

Fix https://github.com/topfunky/gruff/issues/630
This patch provides two ways to make the background transparent.
```ruby
g = Gruff::Bar.new
g.transparent_background = true # use transparent
g.title = 'Hello world'
g.data :Art, [0, 5, 8, 15]
g.data :Philosophy, [10, 3, 2, 8]
g.data :Science, [2, 15, 8, 11]
g.write('bar.png')
```
```ruby
g = Gruff::Bar.new
g.theme = {
colors: [
'#FDD84E',
'#6886B4',
'#72AE6E',
'#D1695E',
'#8A6EAF',
'#EFAA43',
'white'
],
marker_color: 'white',
font_color: 'white',
background_colors: nil # use transparent
}
g.title = 'Hello world'
g.data :Art, [0, 5, 8, 15]
g.data :Philosophy, [10, 3, 2, 8]
g.data :Science, [2, 15, 8, 11]
g.write('bar.png')
```

Add the way to make background transparent

---

.github/ISSUE_TEMPLATE/report.yml

The template used so far has been obsoleted and it is no longer available.
So, this PR will add new template.

GitHub: Add new issue template
